### ISSUE TITLE
vapoursynth.Error: RIFE: gpu_thread must be between 1 and 1 (inclusive)

### ISSUE THREAD

**Issue by pieboy1101** [mafiosnik777/enhancr#35]
I cannot run any interpolation, upscale, or restore models. Logs below. I have an integrated GPU and a dedicated GPU. I used this installer https://github.com/mafiosnik777/enhancr/releases/download/0.9.9/enhancr-setup-free-0.9.9.exe

•─────────•°• enhancr •°•─────────•
OS: Microsoft Windows 11 Home x64
CPU: Intel Core™ i5-10500H | [6C/12T]
RAM: 16173 MB
GPU: NVIDIA GeForce RTX 3060 Laptop GPU | 6144 MB
Status: Ready
•°•────────────────────────────────•°•
[enhancr] 'XMassTestClip.mp4': Successfully added to Queue
[enhancr] Encoding parameters: -c:v h264_nvenc -preset p6 -b_adapt 1 -rc-lookahead 30 -qp 18 -qp_cb_offset -2 -qp_cr_offset -2 -pix_fmt nv12
[enhancr] Model: RIFE - v4.6
[enhancr] Starting interpolation process..

[Pipe] [0 Intel(R) UHD Graphics]  queueC=0[1]  queueG=0[1]  queueT=0[1]
[0 Intel(R) UHD Graphics]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[0 Intel(R) UHD Graphics]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[0 Intel(R) UHD Graphics]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[Pipe] [1 NVIDIA GeForce RTX 3060 Laptop GPU]  queueC=2[8]  queueG=0[16]  queueT=1[2]
[1 NVIDIA GeForce RTX 3060 Laptop GPU]  bugsbn1=0  bugbilz=0  bugcopc=0  bugihfa=0
[1 NVIDIA GeForce RTX 3060 Laptop GPU]  fp16-p/s/a=1/1/1  int8-p/s/a=1/1/1
[1 NVIDIA GeForce RTX 3060 Laptop GPU]  subgroup=32  basic=1  vote=1  ballot=1  shuffle=1
[Pipe] Script evaluation failed:
Python exception: RIFE: gpu_thread must be between 1 and 1 (inclusive)

Traceback (most recent call last):
  File "src\cython\vapoursynth.pyx", line 3115, in vapoursynth._vpy_evaluate
  File "src\cython\vapoursynth.pyx", line 3116, in vapoursynth._vpy_evaluate
  File "D:\Videos\enhancr\resources\inference\rife.py", line 67, in <module>
    clip = core.rife.RIFE(clip, model=model, factor_num=2, gpu_id=0, gpu_thread=threading(), tta=TTA, uhd=UHD, skip=frameskip, sc=sceneDetection)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "src\cython\vapoursynth.pyx", line 2847, in vapoursynth.Function.__call__
vapoursynth.Error: RIFE: gpu_thread must be between 1 and 1 (inclusive)
[Pipe] 
[enhancr] An error has occured.
[enhancr] Completed queue with 1 error(s).

**Comment by samconrad** [comment]
Does this still occur for you when you set Settings (Page 3) > Inference > 1 Concurrent Streams?

**Comment by pieboy1101** [comment]
The concurrent streams did not fix this. I did find out how to make it work though. I am using a laptop with an iGPU and a dedicated GPU. The laptop screen is, I guess, plugged into the iGPU. So no monitor is plugged into the dedicated GPU. In this case, enhancr always fails to run. BUT, if I plug in a monitor, enhancr works. Nvidia Control panel now shows the dedicated GPU plugged in at this point. So it seems something must be plugged into the dedicated GPU for enhancr to work. I wonder if this is easy to make work on your end. Good luck!
![image](https://github.com/mafiosnik777/enhancr/assets/147593889/08c9baf5-336f-4a21-b891-9ce811cf6aa8)
